- platform: Chrome
  version: 3.0.0
  date: 2014-01-28 00:00:00 -0600
  icon: ion-earth
  enabled: No

- platform: Android
  version: 1.0
  date: 2014-01-26 21:00:00 -0600
  icon: ion-social-android
  url: https://play.google.com/store/apps/details?id=com.patil.quickhac
  enabled: Yes

- platform: iOS
  version: 1.0
  date: 2014-01-29 10:00:00 -0600
  icon: ion-social-apple
  url: https://itunes.apple.com/us/app/quickhac/id789578366
  enabled: Yes
